import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from "../src/components/header";
import Main from "../src/components/main";
import Footer from "../src/components/footer";

import "../src/styles/globals.css";
import Theme from "@/src/components/theme";

const geistSans = Geist({
  variable: "--font1",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font2",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Theme 
            attribute="class" 
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange>

          <Header />
          <Main>{children}</Main>
          <Footer />
          
        </Theme>
      </body>
    </html>
  );
}
